# Generated by Django 4.2.4 on 2023-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_read_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='reminder_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
