# Generated by Django 4.2.2 on 2023-08-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_reminder_sent_lead_reminder_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
