# Generated by Django 4.2.4 on 2023-08-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0001_initial'),
        ('leads', '0005_alter_lead_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multi_company.company'),
            preserve_default=False,
        ),
    ]
