# Generated by Django 4.1.1 on 2023-08-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_lead_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookfetchLead',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('leads.lead',),
        ),
    ]
