# Generated by Django 4.1.1 on 2023-09-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_facebookfetchlead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookfetchLead',
        ),
    ]
