# Generated by Django 4.2.4 on 2023-09-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_delete_facebookfetchlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('imported', 'Imported')], default='other', max_length=20),
        ),
    ]
