# Generated by Django 4.2.4 on 2023-09-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('imported', 'Imported')], default='imported', max_length=100),
        ),
    ]
