# Generated by Django 4.2.4 on 2023-09-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_lead_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook_page_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
