# Generated by Django 4.2.4 on 2023-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_facebook_page_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100)),
                ('page_name', models.CharField(max_length=100)),
            ],
        ),
    ]
