# Generated by Django 4.2.4 on 2023-09-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_facebookpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='facebook_page_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.facebookpage'),
        ),
    ]
