# Generated by Django 4.1.1 on 2023-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_remove_lead_facebook_page_name_lead_facebook_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
