# Generated by Django 4.2.4 on 2023-09-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_leadassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadassignment',
            name='avez_vous_travaille',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadassignment',
            name='date_de_soumission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadassignment',
            name='nom_de_la_campagne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadassignment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('expired', 'Expired')], default='new', max_length=20),
        ),
    ]
