# Generated by Django 4.2.4 on 2023-09-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_leadassignment_avez_vous_travaille_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadassignment',
            name='avez_vous_travaille',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
