# Generated by Django 4.2.4 on 2023-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_alter_leadassignment_avez_vous_travaille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadassignment',
            name='status',
        ),
        migrations.AlterField(
            model_name='leadassignment',
            name='date_de_soumission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadassignment',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
