# Generated by Django 4.2.4 on 2023-09-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_remove_leadassignment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadAssignment',
        ),
    ]
