# Generated by Django 4.2.4 on 2023-09-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0020_alter_doisser_numero_edof'),
        ('leads', '0033_remove_facebookpage_users_facebookpage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistory',
            name='doisser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_history_entries', to='multi_company.doisser'),
        ),
    ]
