# Generated by Django 4.2.4 on 2023-09-29 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0037_lead_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacebookPageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_fetch', models.BooleanField(default=False)),
                ('facebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.facebookpage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'facebook_page')},
            },
        ),
    ]
