# Generated by Django 4.2.4 on 2023-10-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0043_alter_facebookpage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pages', models.ManyToManyField(to='leads.facebookpage')),
            ],
        ),
    ]
