# Generated by Django 4.2.4 on 2023-10-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0044_pagegroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageGroup',
        ),
    ]
