# Generated by Django 4.2.4 on 2023-10-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0045_delete_pagegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='page_name',
            field=models.CharField(default='Global Page', max_length=100),
        ),
    ]
