# Generated by Django 4.2.4 on 2023-10-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0046_alter_facebookpage_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='page_name',
            field=models.CharField(max_length=100),
        ),
    ]
