# Generated by Django 4.2.4 on 2023-10-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0049_remove_facebookpage_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='qualification',
            field=models.CharField(blank=True, choices=[('nrp1', 'NRP1'), ('nrp2', 'NRP2'), ('nrp3', 'NRP3'), ('en_cours', 'En cours'), ('rappel', 'Rappel'), ('demande_de_documentation', 'Demande de documentation '), ('faux_numero', 'Faux numéro'), ('pas_de_budget', 'Pas de budget'), ('pas_interesse', 'Pas intéressé'), ('ne_pas_rappele', 'Ne pas rappeler'), ('signe_pole_emploi', 'Signé Pôle Emploi'), ('signe_cpf', 'Signé CPF')], max_length=100, null=True),
        ),
    ]
