# Generated by Django 4.2.4 on 2023-10-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0052_remove_lead_document_lead_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='documents',
        ),
        migrations.AddField(
            model_name='lead',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='leads.document'),
        ),
    ]
