# Generated by Django 4.2.4 on 2023-10-24 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0053_remove_lead_documents_lead_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(related_name='facebook_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
