# Generated by Django 4.2.4 on 2023-10-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0054_facebookpagegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpagegroup',
            name='associated_pages',
            field=models.ManyToManyField(related_name='groups', to='leads.facebookpage'),
        ),
    ]
