# Generated by Django 4.2.4 on 2023-10-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0055_facebookpagegroup_associated_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpage',
            name='user',
        ),
    ]
