# Generated by Django 4.2.4 on 2023-10-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0059_usergrouppermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.facebookpagegroup'),
            preserve_default=False,
        ),
    ]
