# Generated by Django 4.2.4 on 2023-09-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusertypes_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertypes',
            name='can_fetch_from_facebook_page',
            field=models.BooleanField(default=False),
        ),
    ]
