# Generated by Django 4.2.4 on 2023-09-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customusertypes_can_fetch_from_facebook_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusertypes',
            name='can_fetch_from_facebook_page',
        ),
    ]
