# Generated by Django 4.2.4 on 2023-09-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customusertypes_can_fetch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusertypes',
            name='can_fetch',
        ),
    ]
