# Generated by Django 4.2.4 on 2023-09-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customusertypes_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertypes',
            name='can_fetch',
            field=models.BooleanField(default=False),
        ),
    ]
