# Generated by Django 4.2.4 on 2023-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelEffectueLe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('motifs', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doisser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dinscription', models.DateField(blank=True, null=True)),
                ('numero_edof', models.IntegerField(blank=True, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=250, null=True)),
                ('address_postal', models.CharField(blank=True, max_length=300, null=True)),
                ('statut_edof', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge', models.CharField(blank=True, max_length=300, null=True)),
                ('colis_a_preparer', models.CharField(blank=True, max_length=300, null=True)),
                ('prix_net', models.IntegerField(blank=True, null=True)),
                ('conseiller', models.CharField(blank=True, max_length=100, null=True)),
                ('equipes', models.CharField(blank=True, max_length=100, null=True)),
                ('criteres_com', models.IntegerField(blank=True, null=True)),
                ('date_prevue_d_entree_en_formation', models.DateField(blank=True, null=True)),
                ('date_prevue_de_fin_de_formation', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionVisioEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.BooleanField()),
                ('niveau_de_relance', models.CharField(blank=True, max_length=100, null=True)),
                ('somme_facturee', models.IntegerField(blank=True, null=True)),
                ('date_de_facturation', models.DateField(blank=True, null=True)),
                ('date_d_encaissement', models.DateField(blank=True, null=True)),
                ('facture', models.BooleanField()),
                ('num_facture', models.BooleanField(blank=True, null=True)),
                ('colis_a_envoyer_le', models.DateField(blank=True, null=True)),
                ('numero_de_suivi_vers_point_relais', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaires', models.CharField(blank=True, max_length=300, null=True)),
                ('statut_colis', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RdvConfirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateandtime', models.DateTimeField(blank=True, null=True)),
                ('confirmateur', models.CharField(blank=True, max_length=100, null=True)),
                ('statut_service_confirmateur', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
