# Generated by Django 4.2.4 on 2023-09-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0003_alter_inscriptionvisioentree_num_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doisser',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doisser',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
