# Generated by Django 4.2.4 on 2023-09-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0004_alter_doisser_nom_alter_doisser_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='doisser',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
