# Generated by Django 4.2.4 on 2023-09-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0005_doisser_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doisser',
            name='criteres_com',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doisser',
            name='numero_edof',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doisser',
            name='prix_net',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doisser',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
