# Generated by Django 4.2.4 on 2023-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0007_alter_inscriptionvisioentree_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionvisioentree',
            name='facture',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptionvisioentree',
            name='num_facture',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
