# Generated by Django 4.2.4 on 2023-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0008_alter_inscriptionvisioentree_facture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppelEffectueLe',
        ),
        migrations.DeleteModel(
            name='InscriptionVisioEntree',
        ),
        migrations.DeleteModel(
            name='RdvConfirme',
        ),
        migrations.AddField(
            model_name='doisser',
            name='appel_effectue_le_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='appel_effectue_le_motifs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_audio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_colis_a_envoyer_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_commentaires',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_date_d_encaissement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_date_de_facturation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_facture',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_niveau_de_relance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_num_facture',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_numero_de_suivi_vers_point_relais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_somme_facturee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='inscription_visio_entree_statut_colis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='rdv_confirme_confirmateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='rdv_confirme_dateandtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doisser',
            name='rdv_confirme_statut_service_confirmateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
