# Generated by Django 4.2.4 on 2023-09-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0009_delete_appeleffectuele_delete_inscriptionvisioentree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doisser',
            name='inscription_visio_entree_num_facture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
