# Generated by Django 4.2.4 on 2023-09-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0014_alter_doisser_appel_effectue_le_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doisser',
            name='appel_effectue_le_date_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doisser',
            name='rdv_confirme_dateandtime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
