# Generated by Django 4.2.4 on 2023-09-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0018_alter_doisser_appel_effectue_le_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doisser',
            name='date_prevue_d_entree_en_formation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
