# Generated by Django 4.2.4 on 2023-09-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0019_alter_doisser_date_prevue_d_entree_en_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doisser',
            name='numero_edof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
