# Generated by Django 4.2.4 on 2023-09-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_leadhistory_doisser'),
        ('multi_company', '0020_alter_doisser_numero_edof'),
    ]

    operations = [
        migrations.AddField(
            model_name='doisser',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doissers', to='leads.leadhistory'),
        ),
    ]
