# Generated by Django 4.2.4 on 2023-09-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0037_lead_company'),
        ('multi_company', '0022_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='doisser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.company'),
        ),
    ]
