# Generated by Django 4.2.4 on 2023-10-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0023_doisser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_soumission', models.DateField(blank=True, null=True)),
                ('nom_de_la_campagne', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('prix_net', models.BigIntegerField(blank=True, null=True)),
                ('conseiller', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
