# Generated by Django 4.2.4 on 2023-10-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0024_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='prix_net',
        ),
        migrations.AddField(
            model_name='formation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
