# Generated by Django 4.2.4 on 2023-10-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0049_remove_facebookpage_user_name'),
        ('multi_company', '0025_remove_formation_prix_net_formation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.company'),
        ),
        migrations.CreateModel(
            name='FormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.company')),
            ],
        ),
    ]
