# Generated by Django 4.2.4 on 2023-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0026_formation_company_formsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='JotFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('signature', models.TextField()),
                ('numero_et_rue', models.CharField(max_length=255)),
                ('complement_adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('etat_region', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('choix_formation', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_heure', models.IntegerField()),
                ('prix_formation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passage_au', models.CharField(max_length=255)),
                ('conseiller', models.CharField(max_length=255)),
                ('formation', models.CharField(max_length=255)),
                ('audio_appel_qualite', models.URLField()),
                ('audio_suivi_formation', models.URLField()),
            ],
        ),
    ]
