# Generated by Django 4.2.4 on 2023-10-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0027_jotformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotformsubmission',
            name='audio_appel_qualite',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='audio_suivi_formation',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='choix_formation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='complement_adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='conseiller',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='etat_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='formation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='nombre_heure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='numero_et_rue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='passage_au',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='prix_formation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
