# Generated by Django 4.2.4 on 2023-10-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0028_alter_jotformsubmission_audio_appel_qualite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jotformsubmission',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
