# Generated by Django 4.2.4 on 2023-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0029_jotformsubmission_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotformsubmission',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
