# Generated by Django 4.2.4 on 2023-10-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0032_alter_jotformsubmission_date_debut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jotformsubmission',
            old_name='conseiller',
            new_name='numero_telephone',
        ),
        migrations.RenameField(
            model_name='jotformsubmission',
            old_name='telephone',
            new_name='votre_conseiller',
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='audio_appel_qualite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='audio_suivi_formation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='code_postal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='nombre_heure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='prix_formation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
