# Generated by Django 4.2.4 on 2023-10-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0033_rename_conseiller_jotformsubmission_numero_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jotformsubmission',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='jotformsubmission',
            name='complement_adresse',
        ),
        migrations.RemoveField(
            model_name='jotformsubmission',
            name='etat_region',
        ),
        migrations.RemoveField(
            model_name='jotformsubmission',
            name='numero_et_rue',
        ),
        migrations.RemoveField(
            model_name='jotformsubmission',
            name='ville',
        ),
        migrations.AddField(
            model_name='jotformsubmission',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
