# Generated by Django 4.2.4 on 2023-10-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0034_remove_jotformsubmission_code_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotformsubmission',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
