# Generated by Django 4.2.4 on 2023-10-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0035_alter_jotformsubmission_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotformsubmission',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
