# Generated by Django 4.2.4 on 2023-10-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0036_alter_jotformsubmission_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotformsubmission',
            name='audio_appel_qualite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='audio_suivi_formation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='choix_formation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='date_debut',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='date_fin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='formation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='nombre_heure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='numero_telephone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='passage_au',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='prix_formation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='submission_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jotformsubmission',
            name='votre_conseiller',
            field=models.TextField(blank=True, null=True),
        ),
    ]
