# Generated by Django 4.2.4 on 2023-10-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0037_alter_jotformsubmission_audio_appel_qualite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jotformsubmission',
            name='data_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
