# Generated by Django 4.2.4 on 2023-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0039_jotformsubmission_aa'),
    ]

    operations = [
        migrations.CreateModel(
            name='JotForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
