# Generated by Django 4.2.4 on 2023-10-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_company', '0042_jotformsubmission_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotformsubmission',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
